BIN=snake.exe
LISP=sbcl
BUNDLE=bundle
LIBS=:sdl2 :cl-opengl
BNFLAGS=--no-sysinit --non-interactive \
        --eval "(ql:quickload '($(LIBS)))" \
        --eval "(ql:bundle-systems '($(LIBS)) :to \"$(BUNDLE)/\")" \
        --eval '(exit)'
BUILDFLAGS=--no-sysinit --no-userinit --non-interactive \
	   --load "win-com.lisp"

all: $(BIN)

$(BIN): $(BUNDLE)
	$(LISP) $(BUILDFLAGS)

$(BUNDLE):
	$(LISP) $(BNFLAGS)

clean_all:
	rm -rf $(BIN) $(BUNDLE)

clean:
	rm -f $(BIN)
